### ISSUE TITLE
trouble with @import

### ISSUE THREAD

**Issue by ezmiller** [docpad-archive/extras#13]
Hi,
I'm trying to use @import in a LESS stylesheet within Docpad. The stylesheet is called 'style.css.less' and is located in the /src/documents directory. In that directory, I also have a file 'grid.less' that I try to import into 'style.css.less' with the following line:

```
@import 'grid.less';
```

This however doesn't seem to achieve the import. When I generate the site (docpad generate), the 'grid.less' file is in the /out directory, which I would like to avoid, and the style.css, does not include the contents of 'grid.less.'  

My question is two-fold then. How do I achieve the import of grid.less, and how do I make grid.less available for import without it being transfered to the /out directory.

**Comment by ezmiller** [comment]
Solved. The problem was that I had an error in the grid.less file. Just wasn't being reported by less or docpad.

**Comment by balupton** [comment]
@ezmiller hrmm, that is pretty bad how it isn't reported. I wonder if there is something we can do about that. I've opened up the issue bevry/docpad#279 to look into it :)
