### ISSUE TITLE
Plugin name convention : related != relations

### ISSUE THREAD

**Issue by Delapouite** [docpad-archive/extras#26]
Hi.

Since docpad 6.7.3, warnings about naming convention are raised :
https://github.com/bevry/docpad/issues/313

The related plugin has this issue :
_The plugin related is using a different name (relations) for its prototype name._
https://github.com/bevry/docpad-extras/tree/master/plugins/related

**Comment by balupton** [comment]
Fixed with v2.0.3 of the related plugin. Thanks!
