### ISSUE TITLE
Split each plugin into submodule on the docpad organisation

### ISSUE THREAD

**Issue by balupton** [docpad-archive/extras#27]
After a discussion with @chase earlier about submodules, I want to gather some feedback on the following.

Currently we have all the plugins as part of the the `docpad-extras` repo, this is good for collaboration, management, testing, but bad for tagging, isolation.

It was proposed earlier that the plugins should be owned by the respective authors, and have submodules inside the docpad-extras repo, this is good for tagging, isolation, but bad for collaboration, management, testing.

Thinking about this more, what about plugins should be owned by the [docpad organisation](https://github.com/docpad), and have submodules inside the docpad-extras repo for officially support plugins, this is good for tagging, isolation, collaboration, management, and testing. And bad for none.

If no one has an objection to this, lets do this right away. Happy to give the appropriate access to whoever is willing to make this change.

Important things for this change:
- Keeping the history for ONLY THAT plugin when isolating it into it's own repo
- Will need to add a submodule init, update, checkout thing inside the makefile

/cc @chase @ncrohn @georgeOsdDev @iammerrick @pismute @DjebbZ

**Comment by chase** [comment]
I think that it is certainly a move in the right direction.

At this point, keeping the history for _only_ a specific plugin may be difficult as some commits modify files for more than one plugin. For example: 6c765e845a66ad59e9b62905fc151d90ece27aa4

I will look into splitting a subtree's history this weekend and report back here unless somebody beats me to it.

**Comment by balupton** [comment]
@chase yeah that will be the tricky bit, I know it is possible, as say if you commit a sensitive file to the repo with a bunch of other files, you can tell git to remove that file from all commits as if it never happened. It will be more or less the same thing. But we do risk damaging the history though, but it is better than having huge ancient changelogs.

**Comment by chase** [comment]
I found a blog post that seems to cover a situation similar to our own:
[Modular git with "git subtree"](http://log.pardus.de/2012/08/modular-git-with-git-subtree.html)

**Comment by balupton** [comment]
Completed. All plugins that were in docpad-extras have now moved to their own repos here:
https://github.com/docpad

Will update the testing scripts in this repo (docpad-extras) to react accordingly.

**Comment by balupton** [comment]
Testing script has been updated.
