### ISSUE TITLE
stylus plugin: nib support not functional

### ISSUE THREAD

**Issue by robokaso** [docpad-archive/extras#31]
I started using the stylus plugin which promises out-of-box nib support, but nib functions have no effect, they remain unprocessed in the css output (built-in stylus functions work as expected).

**Comment by robokaso** [comment]
sorry, my bad... I was missing `@import 'nib'`, perhaps it's worth pointing that out in the stylus plugin docs

**Comment by chase** [comment]
This is a valid point, the README does seem a bit ambiguous.

I'm going to update it clarify its usage until Ben approves a patch to automatically import it.
