### ISSUE TITLE
REST plugin doesn't respond because of empty Collection.

### ISSUE THREAD

**Issue by DjebbZ** [docpad-archive/extras#7]
The REST plugin searches for document using QueryEngine. I'm rewriting it (just updating it to DocPad v6), and I'm placing various `docpad.log <something>`. I followed your advice (@balupton) of adding `docpad = @docpad` at the beginning. I rewrote the querying line to 

``` coffee
docpad.getCollection('documents').findOne url: req.url, (err,document) ->
```

to match the new API.

Problem : logging `docpad.getCollection('documents')` returns an empty array (`[]`), whereas I do have one `index.html.md` document in `src/documents`, that uses a basic `default` layout. Since there's no collection, I think the callback function of `findOne` never gets executed, because all log statements inside never show. And so the call to `res.send JSON.stringify {success:true}` never happens, and the POST query times out. I tried to POST both with `jQuery.post` (jQuery 1.7.2 is included in the layout) and Curl with this basic command : 

``` shell
curl -v -X POST -d '{"title":"Title","content":"Hello World"}' http://localhost:9778/
```

and Curl answers this :

``` shell

* About to connect() to localhost port 9778 (#0)
*   Trying 127.0.0.1... connected
* Connected to localhost (127.0.0.1) port 9778 (#0)
> POST / HTTP/1.1
> User-Agent: curl/7.19.7 (universal-apple-darwin10.0) libcurl/7.19.7 OpenSSL/0.9.8r zlib/1.2.3
> Host: localhost:9778
> Accept: */*
> Content-Length: 41
> Content-Type: application/x-www-form-urlencoded
> 
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
* Closing connection #0
```

Note that the last lines starting with `*` appear some time after issueing the command, that's the time out.

In both POST queries (jQuery and Curl), no error appears neither in the console nor the terminal that launched the server.

Not sure if it's a problem with the plugin or `docpad.getCollection('documents')` itself...

**Comment by DjebbZ** [comment]
See this commit in the `rest` branch of my fork : https://github.com/DjebbZ/docpad-extras/commit/4fbe1c5e3d0b3af416b73c6ec67e0320d6bc2b36

**Comment by balupton** [comment]
closing due to age
